import HomeScreen from './screens/HomeScreen';
import WarisScreen from './screens/WarisScreen';
import TransaksiScreen from './screens/TransaksiScreen';
import KematianScreen from './screens/KematianScreen';
import PlaylistScreen from './screens/PlaylistScreen';
import PesertaScreen from './screens/PesertaScreen';
import PertubuhanScreen from './screens/PertubuhanScreen';
import EmergencyLogScreen from './screens/EmergencyLogScreen';
import DaftarPesertaScreen from './screens/DaftarPesertaScreen';
